# Senkey Slopegraph

In order to create this chart, we are going to prepare our data using python. We will use sigmoid to create a connecting line. Once we finish this, we will import computed data to Tableau for visualization.

Orginal grpah: http://www.neatorama.com/2014/02/25/The-States-of-Happiness/#!BgCd8 <br/>
Reference: http://www.dataplusscience.com/RecreationinTableau2.html

Step for creating visualizatio in tabeau:
* Move t to Columns
* Move Curve to Rows
* Move State to Details
* Move t to Details and Convert to Dimension
* Set Marks to Line

In [1]:
import pandas as pd
import numpy as np

# Loading data

In [2]:
df = pd.read_excel("raw_data.xlsx")

In [3]:
df.head(5)

    Country  Rank 2013  Rank 2015
0  Thailand          1          3
1     China          2          1
2      Fiji          3          4
3     Sudan          4          2
4     Benin          5          7

In [4]:
df.shape

(25, 3)

# Calculate slope line using Sigmoid function

In [5]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [6]:
country = []
oldRank = []
newRank = []
size = []
t = []
excel_sig = []
excel_cur = []
color = []

texcel_sig = 1/df.shape[0]
itt = 12/(df.shape[0]-1)


for index , row in df.iterrows():
    tt = -6
    
    for i in range(df.shape[0]-1):
        country.append(row['Country'])
        oldRank.append(row['Rank 2013'])
        newRank.append(row['Rank 2015'])
        size.append(abs(row['Rank 2015']-row['Rank 2013']))
        color.append(row['Rank 2015']-row['Rank 2013'])
        
        t.append(tt)
        texcel_sig = sigmoid(tt)
        
        excel_sig.append(texcel_sig)
        excel_cur.append(row['Rank 2013'] + ((row['Rank 2015']-row['Rank 2013'])* texcel_sig))
        
        tt = tt + itt

In [7]:
dftab = pd.DataFrame({'Country': country, '2013 Ranking': oldRank, '2015 Ranking':newRank,
                        'Excel Size': size, 'Excel Sigmoid':excel_sig, 't': t,
                        'Excel Calculated Curve': excel_cur, 'color':color
                       })

In [8]:
dftab

,2013 Ranking,2015 Ranking,Country,Excel Calculated Curve,Excel Sigmoid,Excel Size,color,t
0,1,3,Thailand,1.004945,0.002473,2,2,-6.0
1,1,3,Thailand,1.008140,0.004070,2,2,-5.5
2,1,3,Thailand,1.013386,0.006693,2,2,-5.0
3,1,3,Thailand,1.021974,0.010987,2,2,-4.5
4,1,3,Thailand,1.035972,0.017986,2,2,-4.0
5,1,3,Thailand,1.058624,0.029312,2,2,-3.5
6,1,3,Thailand,1.094852,0.047426,2,2,-3.0
7,1,3,Thailand,1.151716,0.075858,2,2,-2.5
8,1,3,Thailand,1.238406,0.119203,2,2,-2.0
9,1,3,Thailand,1.364851,0.182426,2,2,-1.5
10,1,3,Thailand,1.537883,0.268941,2,2,-1.0
11,1,3,Thailand,1.755081,0.377541,2,2,-0.5
12,1,3,Thailand,2.000000,0.500000,2,2,0.0
13,1,3,Thailand,2.244919,0.622459,2,2,0.5
14,1,3,Thailand,2.462117,0.731059,2,2,1.0
15,1,3,Thailand,2.635149,0.817574,2,2,1.5
16,1,3,Thailand,2.761594,0.880797,2,2,2.0
17,1,3,Thailand,2.848284,0.924142,2,2,2.5
18,1,3,Thailand,2.905148,0.952574,2,2,3.0
19,1,3,Thailand,2.941376,0.970688,2,2,3.5
20,1,3,Thailand,2.964028,0.982014,2,2,4.0
21,1,3,Thailand,2.978026,0.989013,2,2,4.5
22,1,3,Thailand,2.986614,0.993307,2,2,5.0
23,1,3,Thailand,2.991860,0.995930,2,2,5.5
24,2,1,China,1.997527,0.002473,1,-1,-6.0
25,2,1,China,1.995930,0.004070,1,-1,-5.5
26,2,1,China,1.993307,0.006693,1,-1,-5.0
27,2,1,China,1.989013,0.010987,1,-1,-4.5
28,2,1,China,1.982014,0.017986,1,-1,-4.0
29,2,1,China,1.970688,0.029312,1,-1,-3.5
...,...,...,...,...,...,...,...,...
570,24,25,Albania,24.952574,0.952574,1,1,3.0
571,24,25,Albania,24.970688,0.970688,1,1,3.5
572,24,25,Albania,24.982014,0.982014,1,1,4.0
573,24,25,Albania,24.989013,0.989013,1,1,4.5
574,24,25,Albania,24.993307,0.993307,1,1,5.0
575,24,25,Albania,24.995930,0.995930,1,1,5.5
576,25,22,Cambodia,24.992582,0.002473,3,-3,-6.0
577,25,22,Cambodia,24.987790,0.004070,3,-3,-5.5
578,25,22,Cambodia,24.979921,0.006693,3,-3,-5.0
579,25,22,Cambodia,24.967039,0.010987,3,-3,-4.5
580,25,22,Cambodia,24.946041,0.017986,3,-3,-4.0
581,25,22,Cambodia,24.912063,0.029312,3,-3,-3.5
582,25,22,Cambodia,24.857722,0.047426,3,-3,-3.0
583,25,22,Cambodia,24.772425,0.075858,3,-3,-2.5
584,25,22,Cambodia,24.642391,0.119203,3,-3,-2.0
585,25,22,Cambodia,24.452723,0.182426,3,-3,-1.5
586,25,22,Cambodia,24.193176,0.268941,3,-3,-1.0
587,25,22,Cambodia,23.867378,0.377541,3,-3,-0.5
588,25,22,Cambodia,23.500000,0.500000,3,-3,0.0
589,25,22,Cambodia,23.132622,0.622459,3,-3,0.5
590,25,22,Cambodia,22.806824,0.731059,3,-3,1.0
591,25,22,Cambodia,22.547277,0.817574,3,-3,1.5
592,25,22,Cambodia,22.357609,0.880797,3,-3,2.0
593,25,22,Cambodia,22.227575,0.924142,3,-3,2.5
594,25,22,Cambodia,22.142278,0.952574,3,-3,3.0
595,25,22,Cambodia,22.087937,0.970688,3,-3,3.5
596,25,22,Cambodia,22.053959,0.982014,3,-3,4.0
597,25,22,Cambodia,22.032961,0.989013,3,-3,4.5
598,25,22,Cambodia,22.020079,0.993307,3,-3,5.0
599,25,22,Cambodia,22.012210,0.995930,3,-3,5.5

In [9]:
dftab.to_csv("senkey_slope_data.csv", index=False)

# Create Visualization.

Once I complete prepaparing the data, I will use this data with tableau. 

Step for creating visualizatio in tabeau:
* Move t to Columns
* Move Curve to Rows
* Move State to Details
* Move t to Details and Convert to Dimension
* Set Marks to Line